spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

worker:
  media:
    streaming-audio-path: ${STREAMING_AUDIO_PATH}
  bootstrap:
    enabled: false
server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
  file:
    path: ${LOG_PATH}

r2:
  account-id: ${R2_ACCOUNT_ID}
  access-key-id: ${R2_ACCESS_KEY_ID}
  secret-access-key: ${R2_SECRET_ACCESS_KEY}
  bucket:
    media: ${R2_BUCKET_MEDIA}
    assets: ${R2_BUCKET_ASSETS}